# Summary: GitHub Actions workflow to run a YAML linter on .yml files.
#
# Copyright 2024 California Institute of Technology.
# License: Modified BSD 3-clause – see file "LICENSE" in the project website.
# Website: https://github.com/caltechlibrary/devonthink-hacks

name: YAML file linter

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.yml'
      - '**.yaml'
  push:
    branches:
      - main
    paths:
      - '**.yml'
      - '**.yaml'

run-name: Run linter on YAML files
jobs:
  Yamllint:
    name: GitHub YAMLlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out copy of git repository
        uses: actions/checkout@v4

      - name: Run YAMLlint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml
